# Generated by Django 3.2.6 on 2021-11-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartlist_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartlist'),
        ),
    ]
